### ISSUE TITLE
Suspicious dependencies

### ISSUE THREAD

**Issue by androlo** [eris-ltd/decerver-modules#1]
The eth module has a dependency to epm-go/utils to do some config stuff. I'm pretty sure both it and monk will use epm-go in some way in the future, so maybe this is not important.

The ipfs module has a dependency to decerver/interfaces/modules in the file impl/ipfs.go. This should be removed. Impl is supposed to be independent of decerver or any module stuff. The reason it's there is to speed up the generation of trees, by making the nodes JsObjects directly, so that they can be passed directly into ate. I will continue to do that, but use a generic map instead (not the modules.JsObject type), and then pass it in via the normal conversion method. This will add the time it takes for conversion, but conversion will not do anything other then validate, which imo should be done anyways.

**Comment by ebuchman** [comment]
ok ya so we should standardize a place for general util stuff. the things in `epm-go/utils` are for example hardcoded paths to the important things in the go source tree and in the ~/.decerver directory, as well as functions for creating the decerver directory, and other simple things. happy to move that out of epm but we dont really have a standard place anymore. i kind of liked decerver-interfaces as our place for such things but not sure now.

**Comment by dennismckinnon** [comment]
test

**Comment by androlo** [comment]
Decerver has standard functions for loading and saving json files now, such as for example config and package.json files. It's part of the FileIO interface. It is exported to modules in the Register method, so it can be used for module making and also in decerver itself. Having some third party stuff for the actual file reading/writing would be awesome though. It could have special config stuff, package stuff etc. FileIO has decerver specific functions like decerver paths, and is not really generic. It could call methods from a generic library though.

**Comment by androlo** [comment]
Maybe we should have something for logging too.

**Comment by ebuchman** [comment]
right so I have some functions to do do the reflect crap on the json structs for setting propertys and all that jazz, and all my modules use it. I believe still in epm-go/utils.

Should we just have an `eris-ltd/utils` ? @group

**Comment by androlo** [comment]
There are other things in this issue too, that I have to deal with. Re opening.

**Comment by compleatang** [comment]
deprecated
